# Generated by Django 5.1.6 on 2025-04-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiterapp', '0002_remove_staff_is_waiter_staff_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(unique=True)),
                ('seats', models.IntegerField()),
                ('is_reserved', models.BooleanField(default=False)),
            ],
        ),
    ]
