# Generated by Django 5.1.6 on 2025-04-17 18:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiterapp', '0003_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='seats',
            field=models.IntegerField(default=4),
        ),
    ]
